### ISSUE TITLE
Cannot Format (Unibeautify 0.8.0 on vscode 1.44.2)

### ISSUE THREAD

**Issue by sagarpanchal** [Unibeautify/vscode#262]
### Issue
```
Extension 'Unibeautify - Universal Formatter' cannot format 'index.js'
```

> Downgrading to 0.7.0 or 0.6.1 works fine

### VSCode details

- Version: 1.44.2 (system setup)
- Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
- Date: 2020-04-16T16:36:23.138Z
- Electron: 7.1.11
- Chrome: 78.0.3904.130
- Node.js: 12.8.1
- V8: 7.8.279.23-electron.0
- OS: Windows_NT x64 10.0.18363

**Comment by sagarpanchal** [comment]
### `.unibeautifyrc.yml`

```yml
---
# MarkUp
HTML:
  beautifiers:
    - Pretty Diff
    - JS-Beautify
  end_with_newline: true

Markdown:
  beautifiers:
    - Prettier
  indent_style: space

# StyleSheets
CSS:
  beautifiers:
    - Prettier
    - Pretty Diff
  indent_size: 2
  indent_style: space
  max_preserve_newlines: 1
  newline_between_rules: true
  no_leading_zero: true

SCSS:
  beautifiers:
    - Prettier
    - Pretty Diff
  indent_size: 2
  indent_style: space
  max_preserve_newlines: 1
  newline_between_rules: true
  no_leading_zero: true

# Scripts
JavaScript:
  beautifiers:
    - Prettier
    - ESLint
  end_with_semicolon: false
  max_preserve_newlines: 1
  multiline_ternary: always
  object_curly_spacing: true
  quotes: single
  wrap_line_length: 120

JSX:
  beautifiers:
    - Prettier
    - ESLint
  end_with_semicolon: false
  max_preserve_newlines: 1
  multiline_ternary: always
  object_curly_spacing: true
  quotes: single
  wrap_line_length: 120

TypeScript:
  beautifiers:
    - Prettier
    - Pretty Diff
  end_with_semicolon: false
  max_preserve_newlines: 1
  multiline_ternary: always
  object_curly_spacing: true
  quotes: single
  wrap_line_length: 120

# JSON & GraphQL
JSON:
  beautifiers:
    - Prettier
  indent_size: 2
  indent_style: space
  quotes: double

GraphQL:
  beautifiers:
    - Prettier
```
